server:
  port: 7001

eureka:
  instance:
    hostname: localhost # eureka 服务端名称
  client:
    register-with-eureka: false # 是否向注册中心注册
    fetch-registry: false # false 表示自己为注册中心
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
