server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002 # eureka 服务端名称
  client:
    register-with-eureka: false # 是否向注册中心注册
    fetch-registry: false # false 表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/
